"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowRight, BarChart3, BrainCircuit, Check, ChevronRight, FileCheck2, Languages, Sparkles } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const steps = [
  ["Student profile", "Tell us about the student", "Academic context helps interpret every assessment for the individual student."],
  ["Assessment", "A structured psychological assessment", "Twenty carefully structured questions explore how a student thinks, responds and develops."],
  ["Behavioural journey", "Every answer builds the profile", "Response patterns connect reflection, decisions, communication, learning and adaptability."],
  ["Language accessibility", "Understand it in your language", "Switch between English and Marathi without losing assessment progress."],
  ["AI intelligence", "Responses become intelligence", "The analysis engine converts response patterns into clear developmental insights."],
  ["Intelligence report", "A meaningful student growth report", "Personality, strengths and development priorities become a structured action plan."],
];

function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) {
  return <p className={`text-[11px] font-bold uppercase tracking-[.2em] ${light ? "text-blue-100" : "text-blue-600"}`}>{children}</p>;
}

function HeroVisual() {
  return <div className="relative mx-auto h-[420px] w-full max-w-[520px]" aria-hidden="true">
    <div className="absolute inset-12 rounded-full bg-gradient-to-br from-blue-300/30 to-violet-300/30 blur-3xl" />
    <div className="absolute left-1 top-16 w-[73%] rounded-[26px] border border-slate-200 bg-white p-6 shadow-[0_24px_70px_rgba(37,99,235,.16)]">
      <div className="flex justify-between text-xs font-semibold text-blue-600"><span>PSYCHOMETRIC ASSESSMENT</span><span className="text-slate-400">12 / 20</span></div>
      <div className="mt-4 h-1.5 rounded-full bg-slate-100"><div className="h-full w-3/5 rounded-full bg-gradient-to-r from-blue-500 to-violet-500" /></div>
      <p className="mt-6 text-lg font-semibold">How do you approach an unfamiliar challenge?</p>
      <div className="mt-5 grid gap-2">{["I pause and make a plan", "I ask someone for context", "I begin and adapt"].map((x,i)=><div key={x} className={`rounded-xl border px-3 py-2.5 text-xs ${i===0?"border-blue-400 bg-blue-50 text-blue-700":"border-slate-200 text-slate-500"}`}>{x}</div>)}</div>
    </div>
    <div className="absolute right-0 top-3 rounded-2xl border border-violet-100 bg-white p-4 shadow-xl"><Sparkles className="h-5 w-5 text-violet-500"/><p className="mt-3 text-xs text-slate-500">Personality insight</p><p className="font-semibold">Growth mindset</p></div>
    <div className="absolute bottom-8 right-2 w-48 rounded-2xl border border-blue-100 bg-white p-4 shadow-xl"><div className="flex gap-2"><FileCheck2 className="h-5 w-5 text-emerald-500"/><b className="text-sm">Report ready</b></div><div className="mt-3 flex h-12 items-end gap-1.5">{[35,55,48,76,65,88].map((h,i)=><span key={i} className="flex-1 rounded-t bg-gradient-to-t from-blue-500 to-violet-400" style={{height:`${h}%`}}/>)}</div></div>
  </div>;
}

function Profile() { return <div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-2">{["AGE · 16","GRADE · 10","SECTION · A"].map(x=><span key={x} className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-bold text-blue-700">{x}</span>)}</div><div className="mt-5 grid grid-cols-2 gap-3">{["Full name","Age","Gender","Grade / Class","Section","Email address"].map((x,i)=><div key={x} className={i===0||i===5?"col-span-2":""}><label className="mb-1 block text-[10px] font-semibold text-slate-500">{x}</label><div className="h-10 rounded-xl border border-slate-200 bg-slate-50"/></div>)}</div><button className="mt-5 flex w-full justify-center gap-2 rounded-xl bg-blue-600 py-3 text-xs font-bold text-white">Begin Psychological Assessment <ArrowRight className="h-4 w-4"/></button><p className="mt-2 text-center text-[10px] text-slate-400">Takes less than a minute.</p></div> }

function Assessment() { const dims=["Self Awareness","Decision Making","Adaptability","Self Discipline","Emotional Response","Growth Mindset"]; return <div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-[24px] border border-slate-200 bg-white p-5"><div className="flex justify-between text-[11px] font-semibold text-blue-600"><span>Question 1 of 20</span><span>5%</span></div><div className="mt-3 h-1 bg-slate-100"><div className="h-full w-[5%] bg-blue-600"/></div><p className="mt-5 font-semibold leading-relaxed">How frequently do you reflect on your strengths, weaknesses and academic performance?</p><div className="mt-4 space-y-2">{["Very frequently","Sometimes","Rarely","Almost never"].map((x,i)=><div key={x} className={`rounded-xl border p-3 text-xs ${i===1?"border-blue-500 bg-blue-50 text-blue-700":"border-slate-200 text-slate-600"}`}>{x}</div>)}</div></div><div className="rounded-[24px] bg-[#3f2f7a] p-5 text-white"><b className="text-xs">Assessment Dimensions</b><div className="mt-4 flex flex-wrap gap-2">{dims.map(x=><span key={x} className="rounded-full border border-violet-200/25 bg-white/[.06] px-2.5 py-1.5 text-[10px] text-violet-100">{x}</span>)}</div><p className="mt-5 text-[11px] leading-relaxed text-violet-100/70">Each response contributes to a multidimensional behavioural profile.</p></div></div> }

function Journey() { const obs=["Reflect","React","Decide","Handle setbacks","Learn","Communicate","Plan","Adapt"]; return <div className="grid gap-5 sm:grid-cols-2"><div className="relative h-72">{[10,9,8,7].map((n,i)=><div key={n} className="absolute left-1/2 w-[88%] -translate-x-1/2 rounded-[20px] border border-slate-200 bg-white p-5 shadow-lg" style={{top:i*24,transform:`translateX(-50%) scale(${1-i*.04})`,opacity:1-i*.16,zIndex:5-i}}><b className="text-[10px] text-blue-600">QUESTION {n}</b><p className="mt-3 text-sm font-semibold">When plans change, what do you do first?</p></div>)}</div><div><b className="text-xs">What AI CMT observes</b><div className="mt-4 grid grid-cols-2 gap-2">{obs.map(x=><div key={x} className="flex items-center gap-2 rounded-xl bg-slate-50 p-2.5 text-[11px] text-slate-600"><i className="h-1.5 w-1.5 rounded-full bg-violet-500"/>{x}</div>)}</div></div></div> }

function Language() { const [mr,setMr]=useState(false); const answers=mr?["मी कारण समजून घेतो","मी पुन्हा प्रयत्न करतो","मी मार्गदर्शन घेतो","मी योजना बदलतो"]:["Understand the cause","Try again","Seek guidance","Change the plan"]; return <div className="rounded-[26px] border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><span className="flex gap-2 text-xs font-bold"><Languages className="h-4 w-4 text-blue-600"/>Question 14</span><div className="flex rounded-full bg-slate-100 p-1"><button onClick={()=>setMr(false)} className={`rounded-full px-3 py-1.5 text-[10px] font-bold ${!mr?"bg-white text-blue-600 shadow":"text-slate-500"}`}>ENGLISH</button><button onClick={()=>setMr(true)} className={`rounded-full px-3 py-1.5 text-[10px] font-bold ${mr?"bg-white text-blue-600 shadow":"text-slate-500"}`}>मराठी</button></div></div><p lang={mr?"mr":"en"} className="mt-9 min-h-20 text-xl font-semibold leading-relaxed">{mr?"एखादा निर्णय अपेक्षेप्रमाणे झाला नाही, तर तुमची प्रतिक्रिया कशी असते?":"When a decision doesn't go as planned, how do you usually respond?"}</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{answers.map(x=><div key={x} className="rounded-xl border border-slate-200 p-3 text-xs text-slate-600">{x}</div>)}</div><p className="mt-5 text-xs text-slate-400">Switch languages without losing assessment progress.</p></div> }

function Analysis() { const out=["Personality","Behaviour","Academic readiness","Growth","Decision making","Self awareness","Emotional regulation","Communication","Responsibility","Adaptability"]; return <div className="rounded-[28px] bg-[#3f2f7a] p-6 text-white"><div className="grid items-center gap-7 sm:grid-cols-[.7fr_1fr_1.3fr]"><div className="rounded-2xl border border-violet-200/25 bg-white/[.06] p-4 text-center"><b className="text-3xl">20</b><p className="text-[10px] text-violet-100/70">ASSESSMENT RESPONSES</p></div><div className="cmt-pulse relative mx-auto flex h-32 w-32 items-center justify-center rounded-full bg-gradient-to-br from-[#7c3aed] to-[#a855f7]"><BrainCircuit className="h-10 w-10"/><span className="absolute -bottom-7 text-[10px] font-bold text-violet-100">AI CMT ENGINE</span></div><div className="flex flex-wrap justify-center gap-2">{out.map(x=><span key={x} className="rounded-full border border-violet-200/25 bg-white/[.04] px-2.5 py-1.5 text-[10px] text-violet-100">{x}</span>)}</div></div><p className="mt-10 text-center text-xs text-violet-100/70">Psychometric assessment · developmental insight · behavioural profiling · growth analytics</p></div> }

function Report() { return <div className="mx-auto max-w-lg rounded-[24px] border border-slate-200 bg-white p-7 shadow-[0_30px_70px_rgba(15,23,42,.12)]"><div className="flex justify-between"><div><b className="text-[10px] tracking-wider text-blue-600">AI CMT</b><h4 className="mt-2 max-w-xs text-2xl font-bold">AI Student Personality & Growth Analytics Report</h4></div><FileCheck2 className="h-9 w-9 text-emerald-500"/></div><div className="mt-8 grid grid-cols-3 gap-3">{[78,84,72].map((n,i)=><div key={n} className="rounded-xl bg-slate-50 p-3 text-center"><b className="text-lg">{n}</b><p className="text-[9px] text-slate-400">{["Awareness","Adaptability","Communication"][i]}</p></div>)}</div><p className="mt-7 flex gap-2 text-xs font-bold text-emerald-600"><Check className="h-4 w-4"/>Report ready</p></div> }

function Visual({index}:{index:number}) { return index===0?<Profile/>:index===1?<Assessment/>:index===2?<Journey/>:index===3?<Language/>:index===4?<Analysis/>:<Report/> }

function HowItWorks() { const [active,setActive]=useState(0); const refs=useRef<(HTMLDivElement|null)[]>([]); useEffect(()=>{const ob=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(Number((e.target as HTMLElement).dataset.step))),{rootMargin:"-35% 0px -45%"});refs.current.forEach(x=>x&&ob.observe(x));return()=>ob.disconnect()},[]); return <section id="how-it-works" className="bg-[#f5f7fb] py-24"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Eyebrow>How AI CMT works</Eyebrow><h2 className="mt-3 max-w-2xl text-3xl font-bold tracking-tight sm:text-5xl">One assessment. Multiple layers of student intelligence.</h2><div className="mt-14 grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div>{steps.map((s,i)=><div key={s[0]} data-step={i} ref={el=>{refs.current[i]=el}} className="flex min-h-[46vh] gap-5 py-10"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-xs font-bold ${active===i?"bg-blue-600 text-white shadow-lg":"border border-slate-200 bg-white text-slate-400"}`}>0{i+1}</span><div><Eyebrow>{s[0]}</Eyebrow><h3 className="mt-3 text-2xl font-bold">{s[1]}</h3><p className="mt-3 max-w-sm text-sm leading-7 text-slate-500">{s[2]}</p><div className="mt-5 lg:hidden"><Visual index={i}/></div></div></div>)}</div><div className="sticky top-24 hidden h-[calc(100vh-8rem)] items-center lg:flex"><div className="w-full"><div className="mb-4 flex gap-2">{steps.map((_,i)=><i key={i} className={`h-1 rounded-full ${active===i?"w-10 bg-blue-600":"w-5 bg-slate-200"}`}/>)}</div><Visual index={active}/></div></div></div></div></section> }

const stakeholder={Student:["Personal strengths","Priority habits","Student action plan"],Parent:["Support strategies","Communication cues","Parent guidance"],Counsellor:["Guidance priorities","Development areas","Session direction"],Institution:["Cohort patterns","Readiness indicators","Programme insight"]};
function Stakeholders(){const [active,setActive]=useState<keyof typeof stakeholder>("Student");return <section className="py-24"><div className="mx-auto max-w-[1200px] px-5 sm:px-8"><div className="text-center"><Eyebrow>Multiple perspectives</Eyebrow><h2 className="mt-3 text-3xl font-bold sm:text-5xl">One Student. Multiple Perspectives.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-slate-500">One assessment becomes useful information for every stakeholder involved in the student&apos;s growth.</p></div><div className="mt-12 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{Object.keys(stakeholder).map(n=><button key={n} onClick={()=>setActive(n as keyof typeof stakeholder)} className={`flex items-center justify-between rounded-2xl border p-4 text-left ${active===n?"border-blue-500 bg-blue-50":"border-slate-200"}`}><div><b>{n}</b><p className="mt-1 text-xs text-slate-500">{{Student:"What should I improve?",Parent:"How can I support my child?",Counsellor:"Where is guidance required?",Institution:"What patterns exist across students?"}[n as keyof typeof stakeholder]}</p></div><ChevronRight className="h-4 w-4 text-blue-600"/></button>)}</div><div className="rounded-[28px] border border-slate-200 bg-slate-50 p-6"><div className="rounded-[22px] bg-white p-6 shadow-xl"><div className="flex justify-between border-b border-slate-100 pb-5"><div><Eyebrow>AI CMT report view</Eyebrow><h3 className="mt-1 text-xl font-bold">{active} insights</h3></div><BarChart3 className="text-violet-500"/></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{stakeholder[active].map((x,i)=><div key={x} className="rounded-2xl border border-blue-100 bg-blue-50 p-4"><b className="text-2xl text-blue-600">{[82,76,88][i]}</b><p className="mt-4 text-xs font-semibold">{x}</p></div>)}</div></div></div></div></div></section>}

const insights=[["Self Awareness",82,"Strong awareness of personal behaviour and learning patterns."],["Decision Making",76,"Thoughtful choices with growing confidence under pressure."],["Adaptability",84,"Responds constructively when situations change."],["Communication",71,"Clear expression that improves with preparation."],["Growth Mindset",88,"Highly receptive to feedback and new challenges."]];
function Insights(){const cards=(copy:string)=>insights.map(([n,s,t])=><article key={`${copy}-${n}`} className="w-[290px] shrink-0 rounded-[24px] border border-white/15 bg-white/[.08] p-6 shadow-lg shadow-[#2c2159]/30 sm:w-[340px]"><span className="rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-bold text-[#ddd6fe]">SAMPLE INSIGHT</span><div className="mt-10 flex items-end gap-2"><b className="text-5xl">{s as number}</b><span className="text-violet-200/60">/ 100</span></div><div className="mt-5 h-1.5 rounded bg-white/10"><div className="h-full rounded bg-gradient-to-r from-[#c4b5fd] to-[#a78bfa]" style={{width:`${s}%`}}/></div><h3 className="mt-7 text-lg font-bold">{n}</h3><p className="mt-2 text-xs leading-6 text-violet-100/70">{t}</p></article>);return <section className="overflow-hidden bg-[#3f2f7a] py-24 text-white"><div className="mx-auto max-w-[1240px] px-5 sm:px-8"><Eyebrow light>Personality & growth insights</Eyebrow><h2 className="mt-3 text-3xl font-bold sm:text-5xl">Personality at a glance</h2><p className="mt-4 text-sm text-violet-200/70">Illustrative demo data · Sample Insight</p></div><div className="cmt-marquee mt-12 flex w-max gap-5 pb-5"><div className="flex gap-5" aria-label="Sample personality insights">{cards("primary")}</div><div className="flex gap-5" aria-hidden="true">{cards("duplicate")}</div></div></section>}

export default function ExploreAICMTPage(){return <div className="min-h-screen bg-white text-slate-900"><Navbar/><main><section className="relative overflow-hidden border-b border-slate-100 bg-gradient-to-b from-[#f7faff] to-white py-20 sm:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_35%,rgba(124,58,237,.08),transparent_28%),radial-gradient(circle_at_65%_15%,rgba(37,99,235,.1),transparent_24%)]"/><div className="relative mx-auto grid max-w-[1240px] items-center gap-12 px-5 sm:px-8 lg:grid-cols-[1.05fr_.95fr]"><div><Eyebrow>Explore AI CMT</Eyebrow><h1 className="mt-5 text-4xl font-bold leading-[1.08] tracking-[-.035em] sm:text-6xl lg:text-7xl">Discover the intelligence behind every student.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-500">AI CMT transforms structured psychometric assessments into meaningful personality, behavioural and growth insights for students, counsellors, parents and educational institutions.</p></div><HeroVisual/></div></section><HowItWorks/><Stakeholders/><Insights/></main><Footer/><style jsx global>{`html{scroll-behavior:smooth}@keyframes cp{50%{box-shadow:0 0 70px rgba(99,102,241,.48)}}@keyframes cm{to{transform:translateX(calc(-50% - 10px))}}.cmt-pulse{animation:cp 3s ease-in-out infinite}.cmt-marquee{animation:cm 30s linear infinite}.cmt-marquee:hover{animation-play-state:paused}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.cmt-pulse,.cmt-marquee{animation:none}}`}</style></div>}
